gText_Birch_Welcome::
	.string "Do you know why people pray to\n"
	.string "the heavens?\p"
	.string "It's because the gods down here...\p"
	.string "$"

gText_Birch_Pokemon::
	.string "...never do anything for free.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "In this world it's not easy for\n"
	.string "mortals to afford anything.\p"
	.string "But tomorrow's the ascendancy exam.\p"
	.string "If I can impress one of the gods,\n"
	.string "then they might sponsor me as a trainer.\p"
	.string "I could earn fame.\p"
	.string "I could earn money.\p"
	.string "I could move out of my parents\n"
	.string "basement!\p"
	.string "And with the prayers I've studied there's\n"
	.string "no chance I could fail!\p"
	.string "I just need to make sure I wake up early\n"
	.string "tomorrow...\n"
	.string "\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
