	.align 2
gText_ConfirmSave::
	.string "{COLOR BLUE}Choose a save slot:$"

gText_ConfirmLoad::
	.string "{COLOR BLUE}Load from slot:$"	

gText_AlreadySavedFile::
	.string "There is already a saved file.\n"
	.string "Is it okay to overwrite it?$"

gText_SavingDontTurnOff::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"

gText_PlayerSavedGame::
	.string "Saved to {STR_VAR_3}.$"

gText_DifferentSaveFile::
	.string "WARNING!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\l"
	.string "POKéMON, will be entirely lost.\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"

gText_SaveError::
	.string "Save error$"

gText_SavingDontTurnOffPower::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"
